---
h1:
  font-family: chronicle roman
  font-size: 40px

h2:
  font-family: chronicle roman
  letter-spacing: 2px
  font-size: 20px

h3:
  font-family: chronicle roman
  letter-spacing: 2px
  font-size: 15px

copy1:
  font-family: chronicle roman
  font-size: 16px

copy2:
  font-family: chronicle roman
  font-size: 12px
  letter-spacing: 2px

copy3:
  font-family: engravers regular
  font-size: 12px
  letter-spacing: 2px

