---
title: Designsake Studio
url: https://designsakestudio.com/
description: A strategic design agency that specializes in branding, packaging, web design, and development
keywords: design, graphic design, branding, packaging, web design, identity design, web development, art direction, designsake, san francisco
share: images/share.jpg
repo: https://github.com/acidjazz/sake2
gmap: https://goo.gl/maps/SV3rxDiZoF22
tracking_id: UA-74113827-1
