---
title: Designsake Studio
url: http://www.designsakestudio.com/
description: Boutique design studio that specializes in branding, packaging, web design, and development
keywords: design, graphic design, branding, packaging, web design, web development, art direction, designsake,
image: img/share.jpg
repo: https://github.com/acidjazz/sake2
gmap: https://goo.gl/maps/SV3rxDiZoF22
