folder: eldestilado
title: el destilado
description:
  - The best-kept secret amongst locals and mezcal seeking aficionados, El Destilado is a Oaxaca based speakeasy and mezcaleria blending the truest flavors of Mexico with progressive gastronomy.
  - Vibrant colors and textures of paper and paint imbue the restaurant's identity with a rich sense of culinary traditions and flavors. The copper still logo, casual kraft-paper menus, agave stamped coasters, and playful vintage postcards season the intimate space, inviting locals and visitors alike to partake in an authentic food experience. <a href="http://www.eldestilado.com/">www.eldestilado.com</a>

services:
  - brand identity
  - print
  - Web Design

prev:
  name: "Full Sun"
  folder: fullsun 

next:
  name: "sufferfest beer co"
  folder: sufferfest 

# :12,25s/ElDestilado_\(\d\+\)x\(\d\+\)px_\(\d\+\)..jpg/- image: ElDestilado_\1x\2px_\3.jpg\r\twidth: \1\r\theight: \2
tiles:
  - image: ElDestilado_1076x550px_1.jpg
    width: 1076
    height: 550
    full: true
  - image: ElDestilado_520x366px_2.jpg
    width: 520
    height: 366
    stack: true
    lefT: true
  - image: ElDestilado_527x930px_3.jpg
    width: 527
    height: 930
    right: true
  - image: ElDestilado_520x532px_4.jpg
    width: 520
    height: 532
  - image: ElDestilado_1076x634px_5.jpg
    width: 1076
    height: 634
    full: true
  - image: ElDestilado_520x455px_6.jpg
    width: 520
    height: 455
    left: true
  - image: ElDestilado_527x455px_7.jpg
    width: 527
    height: 455
  - image: ElDestilado_520x641px_8.jpg
    left: true
    clear: true
    width: 520
    height: 641
  - image: ElDestilado_247x304px_9.jpg
    left: true
    width: 247
    height: 304
  - image: ElDestilado_247x304px_10.jpg
    width: 247
    height: 304
  - image: ElDestilado_528x304px_11.jpg
    width: 528
    height: 304
  - image: ElDestilado_520x445px_12.jpg
    left: true
    clear: true
    width: 520
    height: 445
  - image: ElDestilado_527x445px_13.jpg
    width: 527
    height: 445
  - image: ElDestilado_1076x596px_12.jpg
    width: 1076
    height: 596
