folder: fullsun
title: full sun
description:
  - Inspired by California’s warm and invigorating sunshine, Full Sun is a 100% all-natural, sustainably farmed cannabis. Proudly raised under the sunbelt of Humboldt County, this brand’s product line is a result of mellow ocean breezes, towering Redwoods and sun-drenched hillsides, yielding cannabis of unparalleled quality, taste, and performance.
  - We saw an opportunity to shake up the ever-growing cannabis space with a fresh approach full of California soul. The product packaging pairs retro typography with bright colors and modern geometric patterns. A bold gradient inspired by nature’s skies and splashes of gold foil add a burst of premium shine. <a href="https://www.full-sun.com">www.full-sun.com</a>
services:
  - brand identity
  - packaging
  - copywriting
  - web design + development
  - Mobile Apps

next:
  name: "El Destilado"
  folder: eldestilado 

tiles:
  - image: FullSun_684x525px_1.jpg
    width: 684
    height: 525
    left: true

  - image: FullSun_364x525px_2.jpg
    width: 364
    height: 525

  - image: FullSun_1078x537px_3.jpg
    width: 1078
    height: 537
    full: true

  - image: FullSun_512x453px_4.jpg
    left: true
    width: 512
    height: 453

  - image: FullSun_536x453px_5.jpg
    width: 535
    height: 453

  - image: FullSun_1078x537px_6.jpg
    full: true
    width: 1078
    height: 537

  - image: FullSun_512x453px_7.jpg
    left: true
    width: 512
    height: 453

  - image: FullSun_536x208px_8.jpg
    width: 536
    height: 208
    full: true

  - image: FullSun_536x208px_9.jpg
    width: 536
    height: 208
 
