folder: sufferfest
title: sufferfest
description:
    - Sufferfest Beer Company was born out of a need to provide a gluten-removed beer that doesn’t compromise on taste or quality.
    - "We partnered with Sufferfest to design a beer that celebrates the company’s mantra: “medals for a job well done.” The victorious fist icon communicates the brand’s ability to overcome the limitations of using barley in a gluten-free beer. Crisp white cans featuring a line of distinguished color ribbons and bold typography create a winning combination."
services:
  - brand identity
  - strategy
  - packaging
  - print

tiles:
  - image: Sufferfest_684x525px_1.jpg
    width: 684
    height: 525
    left: true
  - image: Sufferfest_364x525px_2.jpg
    width: 364
    height: 525
  - image: Sufferfest_520x366px_3.jpg
    width: 520
    height: 366
    left: true
  - image: Sufferfest_528x366px_4.jpg
    width: 528
    height: 366
    right: true
  - image: Sufferfest_339x530px_5.jpg
    width: 339
    height: 530
    left: true
  - image: Sufferfest_339x530px_6.jpg
    width: 339
    height: 530
    left: true
  - image: Sufferfest_339x530px_7.jpg
    width: 339
    height: 530
  - image: Sufferfest_1072x630px_8.jpg
    width: 1072
    height: 630
    full: true
  - image: Sufferfest_519x457px_9.jpg
    width: 519
    height: 457
    left: true
  - image: Sufferfest_526x207px_10.jpg
    width: 526
    height: 207
    stack: true
  - image: Sufferfest_526x207px_11.jpg
    width: 526
    height: 207
