folder: sufferfest
title: sufferfest
description:
    - DESIGNSAKE STUDIO SAW AN OPPORTUNITY TO SHAKE UP THE EVER-GROWING CANNABIS SPACE WITH A FRESH APPROACH FULL OF CALIFORNIA SOUL. THE DESIGNSAKE TEAM PAIRED RETRO TYPOGRAPHY WITH BRIGHT COLORS AND MODERN GEOMETRIC PATTERNS. A BOLD GRADIENT INSPIRED BY NATURE’S SKIES AND SPLASHES OF GOLD FOIL ADD A BURST OF PREMIUM SHINE.
    - INSPIRED BY CALIFORNIA’S WARM AND INVIGORATING SUNSHINE, FULL SUN IS A 100% ALL-NATURAL, SUSTAINABLY FARMED CANNABIS LINE. PROUDLY RAISED UNDER THE SUNBELT OF HUMBOLDT COUNTY, THIS BRAND’S PRODUCT LINE IS A RESULT OF MELLOW OCEAN BREEZES, TOWERING REDWOODS AND SUN-DRENCHED HILLSIDES, YIELDING CANNABIS OF UNPARALLELED QUALITY, TASTE, AND PERFORMANCE.
services:
  - brand identity
  - packaging
  - art direction

tiles:
  - image: Sufferfest_684x525px_1.jpg
    width: 684
    height: 525
    left: true
  - image: Sufferfest_364x525px_2.jpg
    width: 364
    height: 525
  - image: Sufferfest_520x366px_3.jpg
    width: 520
    height: 366
    left: true
  - image: Sufferfest_528x366px_4.jpg
    width: 528
    height: 366
    right: true
  - image: Sufferfest_339x530px_5.jpg
    width: 339
    height: 530
    left: true
  - image: Sufferfest_339x530px_6.jpg
    width: 339
    height: 530
  - image: Sufferfest_339x530px_7.jpg
    width: 339
    height: 530
  - image: Sufferfest_1072x630px_8.jpg
    width: 1072
    height: 630
    full: true
  - image: Sufferfest_519x457px_9.jpg
    width: 519
    height: 457
    left: true
  - image: Sufferfest_526x207px_10.jpg
    width: 526
    height: 207
    stack: true
  - image: Sufferfest_526x207px_11.jpg
    width: 526
    height: 207
