folder: sumi
title: sumi
description:
    - A casual-chic kimono co., Sumi creates and produces silk and charmeuse botanical print kimonos. Each robe features an original pattern, first sketched by hand, then saturated in rich watercolors using a traditional sumi paintbrush.
    - "The complete redesign of the brand’s visual identity system began with a new name: SUMI. Inspired by the paintbrush used to create each kimonos designs, the new name unveils a deeper connection to the traditions behind Chinese brushwork in calligraphy and painting. Modern typography coupled with ethereal floral designs and a soft color palette, the brand’s new identity is tailored to the tradition of their timeless kimonos."
services:
  - stategy
  - naming
  - copywriting
  - brand identity
  - print


prev:
  name: "sufferfest beer co"
  folder: sufferfest 

next:
  name: "brown estate"
  folder: brown

#:13,28s/\v(\w+)_(\d+)x(\d+)px_(\d+).jpg/- image: \1_\2x\3px_\4.jpg\r\twidth: \2\r\theight: \3

tiles:
  - image: Sumi_520x762px_1.jpg
    width: 520
    height: 762
    lefT: true
  - image: Sumi_527x365px_2.jpg
    width: 527
    height: 365
    right: true
  - image: Sumi_527x365px_3.jpg
    width: 527
    height: 365
    right: true

  - image: Sumi_1079x625px_4.jpg
    width: 1079
    height: 625
    full: true

  - image: Sumi_710x710px_7.jpg
    width: 710
    height: 710
    right: true
  - image: Sumi_339x229px_5.jpg
    width: 339
    height: 229
    stack: true

  - image: Sumi_339x450px_6.jpg
    width: 339
    height: 450

  - image: Sumi_1079x625px_8.jpg
    width: 1079
    height: 625
    full: true

  - image: Sumi_520x762px_9.jpg
    width: 520
    height: 762
    left: true
  - image: Sumi_527x365px_10.jpg
    width: 527
    height: 365
    stack: true
  - image: Sumi_527x365px_11.jpg
    width: 527
    height: 365


  - image: Sumi_710x530px_12.jpg
    width: 710
    height: 530
    left: true
  - image: Sumi_339x530px_13.jpg
    width: 338
    height: 530
    right: true

