folder: urbankitchen
title: urbankitchen
description:
  - A collaborative culinary kitchen teaching its neighbors from around LA how to savor the moment.
  - The redesign of the brand’s identity began with reconnecting to the owner’s Italian roots. Vibrant blues and reds nod to the baroque tiles and terracotta walls found in traditional Italian kitchens. The logotype is inspired by 1930’s vintage Italian pasta packaging. Imagery of the space and candids of the people who fill it garnish the ecommerce site, illuminating the emotional bonds created over food.<a href="https://www.urbankitchen-la.com/">www.urbankitchen-la.com</a>
services:
  - strategy
  - brand identity
  - print
  - Website Design + Development
  - Photography

prev:
  name: "benefit cosmetics "
  folder: benefitcosmetics

next:
  name: "full sun"
  folder: fullsun

#:13,28s/\v(\w+)_(\d+)x(\d+)px_(\d+).jpg/- image: \1_\2x\3px_\4.jpg\r\twidth: \2\r\theight: \3

tiles:
  - image: Urban_684x525px_1.jpg
    left: true
    width: 684
    height: 525
  - image: Urban_364x525px_2.jpg
    width: 364
    height: 525

  - image: Urban_1079x537px_3.jpg
    full: true
    width: 1079
    height: 537

  - image: Urban_534x737px_4.jpg
    width: 534
    height: 737
    left: true

  - image: Urban_517x356px_5.jpg
    width: 514
    height: 356
    right: true

  - image: Urban_517x352px_6.jpg
    width: 514
    height: 352
    right: true

  - image: Urban_1079x655px_7.jpg
    width: 1079
    height: 655
    full: true

  - image: Urban_508x688px_8.jpg
    width: 508
    height: 688
    left: true
  - image: Urba_543x688px_9.jpg
    width: 540
    height: 688
    right: true

  - image: Urban_370x525px_10.jpg
    width: 370
    height: 525
    left: true
    clear: true
  - image: Urban_681x525px_11.jpg
    width: 678
    height: 525

  - image: Urban_1079x537px_12.jpg
    full: true
    width: 1079
    height: 537
